# Generated by Django 5.0.3 on 2024-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Mobile', 1), ('Shoes', 2), ('Clothes', 3), ('Laptop', 4), ('Headphone', 5), ('Watch', 6), ('Camera', 7), ('Toys', 8)], max_length=50, verbose_name='catrgory'),
        ),
    ]
